- packages/components/src/ads.json
- packages/components/src/components/DaCardAd.vue
- packages/components/src/components/DaInsaneAd.vue
- packages/services/src/monetization.ts
When dailynowco/daily-monetization#1 is closed, a referral link will be provided as part of the response.
The ad components should turn the promoted text to a link, in case a referral link is provided.
Closes #3
> feat: navigate to ad referral link

- packages/components/src/styles/buttons.pcss
- packages/components/stories/button.stories.js
- packages/extension/src/routes/Home.vue
When visiting a single source / tag which is not part of the user's feed an "add to feed" button is revealed.
As of this commit, this button didn't follow the style guidelines.
Closes #2
> fix: "add to feed" button should follow style guidelines

- packages/components/__tests__/DaSwitch.js
- packages/components/src/components/DaModeSwitch.vue
- packages/components/src/components/DaSwitch.vue
- packages/extension/__tests__/DaHeader.js
Both `DaModeSwitch` and `DaSwitch` had jagged transition because of an event that was emitted before the transitions finish.
> fix(components): switches had jagged transition

- packages/extension/src/components/DaSidebar.vue
When searching for tags, changing to the publications list and then going back to tags the list kept the results of the last search although query is empty.
> fix(extension): switching to pubs list after searching tags

- packages/components/src/components/DaCardPlaceholder.vue
- packages/components/src/styles/global.pcss
- packages/extension/src/routes/Home.vue
The first post in the feed is mostly a promoted content which takes more time to load than the rest of the feed. This delay causes the cards to flicker and it's pretty annoying.
This PR shows a placeholder while the ad is loading.
Closes #20
> feat(extension): show placeholder while loading ads

- packages/components/__tests__/DaCardPost.js
- packages/components/__tests__/DaInsanePost.js
- packages/components/__tests__/truncate.js
- packages/components/src/components/DaCardPlaceholder.vue
- packages/components/src/components/DaCardPost.vue
- packages/components/src/components/DaInsanePost.vue
- packages/components/src/truncate.js
Use `DaLineClamp` to limit the tags in insane posts to one line.
Closes #25
> fix(components): truncate tags in insane mode

- .gitignore
This PR added `.DS_Store` to ignored files at root directory to ignore it even in subdirectories, currently, it is only added at [/packages/extension/.gitignore](https://github.com/dailynowco/daily-apps/blob/6afce7b9e63a7eb90557af91d127930a3139b6e1/packages/extension/.gitignore#L1).
> :see_no_evil: Add .DS_Store to ignored files

- packages/extension/__tests__/DaDndMessage.js
- packages/extension/__tests__/DaHeader.js
- packages/extension/__tests__/Home.js
- packages/extension/__tests__/ui.js
- packages/extension/src/components/DaDndMessage.vue
- packages/extension/src/components/DaHeader.vue
- packages/extension/src/routes/Home.vue
- packages/extension/src/standalone/App.vue
- packages/extension/src/standalone/standalone.js
- packages/extension/src/store/modules/ui.js
This PR resolves Issue #14.
Added  a DND button on the header that has an option of
"For 1 Hour" and "Until Tomorrow"
The "Until Tomorrow" button sets the DA on DND mode up until 12 AM or 00:00 hours and enables the DA new tab functionality again.
Whenever the DND mode is activated for chrome and firefox they have different behavior as there's a problem when redirecting the firefox tab to `about:home`.
On Chrome, when DND mode is activated, it'll redirect to Chrome's homepage, but on Firefox it'll redirect to `https://google.com` for now until we find a better solution.
Users can deactivate the DND mode after they had recently activated it through the current tab, if that tab is already closed, they could reactivate the DA through the browser's toolbar by clicking the DA icon.
> :sparkles: Add 'Do Not Disturb' mode to the extension

- packages/components/src/common/adMixin.js
- packages/components/src/common/postMixin.js
- packages/components/src/components/DaCardAd.vue
- packages/components/src/components/DaCardPost.vue
- packages/components/src/components/DaInsaneAd.vue
- packages/components/src/components/DaInsanePost.vue
The new mixins hold the common functionality of ad and post accordingly.
Until now this code was duplicated in the insane and card versions and was hard to maintain.
> refactor(extension): create ad and post mixin

- packages/components/src/components/DaLineClamp.vue
By using the `textContent` property instead of `innerHTML`, XSS attack is prevented
Closes dailynowco/daily#116
> fix(components): prevent xss attacks

- packages/extension/__tests__/feed.js
- packages/extension/src/routes/Home.vue
- packages/extension/src/store/modules/feed.js
- packages/services/__tests__/content.ts
- packages/services/src/content.ts
The main feed introduces a method for a user to choose the sorting criteria.
Currently, two options are available by popularity or creation time.
Closes dailynowco/daily#112
> feat(extension): sort main feed by popularity or creation time

- packages/components/package.json
- packages/components/src/components/DaLineClamp.vue
- packages/components/yarn.lock
Upon resizing the `DaLineClamp` component could get into an infinite loop and by that breaking the page and the browser.
Closes dailynowco/daily#128
> fix: cpu consumption when resizing quickly the window

- packages/extension/src/routes/Home.vue
Hi, While fixing the infinite scroll issue, I also wanted to add a feature like this.
I thought **loading spinner** would be good while loading feeds
> added loading spinner to home page

- packages/extension/src/store/modules/feed.js
Checks for duplicate post before adding new page to the feed.
Closes dailydotdev/daily#97
> fix(extension): duplicate post in feed

- packages/components/src/common/adMixin.js
- packages/components/src/common/domHelper.js
- packages/components/src/common/postMixin.js
- packages/components/src/components/DaCardAd.vue
- packages/components/src/components/DaInsaneAd.vue
- packages/components/src/components/DaInsanePost.vue
- packages/components/src/directives/tooltip.js
- packages/extension/src/components/DaSidebar.vue
Until this commit the tooltip was always appended to the body element.
This caused edge cases where the tooltip wasn't scrolled when there was other scrollable element. In this commit, the tooltip is appended to the first scrollable parent of the target element.
Closes dailydotdev/daily#150
> fix(tooltip): append tooltip to the first scrollable parent

- packages/components/src/components/DaLineClamp.vue
Add title attribute to post cards, with the full text of post title.
So that the full title of the post can be seen by hovering on the post.
Resolves dailydotdev/daily#152
> feat(components): add title to post cards

- docker-compose.yml
- wait-for.sh
Add a docker-compose config file that serves different containers needed to start the local environment for development. the containers are:
1. daily-mysql
1. daily-postgres
1. daily-gateway
1. daily-api
* used wait-for.sh script from https://github.com/eficode/wait-for in order to wait for database initialization before running app containers
> chore: add docker-compose file for local dev

- packages/extension/__tests__/DaSidebar.js
- packages/extension/__tests__/Home.js
- packages/extension/__tests__/Step2.js
- packages/extension/__tests__/__snapshots__/DaSidebar.js.snap
- packages/extension/__tests__/feed.js
- packages/extension/__tests__/user.js
- packages/extension/src/common/services.js
- packages/extension/src/components/DaSidebar.vue
- packages/extension/src/graphql/feed.js
- packages/extension/src/graphql/home.js
- packages/extension/src/graphql/sidebar.js
- packages/extension/src/graphql/tags.js
- packages/extension/src/routes/Home.vue
- packages/extension/src/routes/Step2.vue
- packages/extension/src/standalone/standalone.js
- packages/extension/src/store/index.js
- packages/extension/src/store/modules/feed.js
- packages/extension/src/store/modules/user.js
- packages/extension/src/store/plugins/cache.js
- packages/extension/src/store/plugins/sync.js
- packages/moderator/__tests__/user.js
- packages/moderator/src/common/services.js
- packages/moderator/src/store/index.js
- packages/moderator/src/store/modules/user.js
- packages/services/__tests__/content.ts
- packages/services/src/content.ts
Add prioritization mechanism for fetching data when application is booting.
First level is critical data like feed and authentication details.
Second level is operational data like sources and tags.
Last level is engagement data like notifications and promotional banner.
> refactor: prioritize fetching on boot

- packages/extension/src/components/DaSidebar.vue
If the source name is too long it will be truncated with ellipsis method
Closes #122
> fix: truncate text in sidebar

- packages/components/src/components/DaDropdown.vue
- packages/extension/__tests__/DaSidebar.js
- packages/extension/src/components/DaIntegrations.vue
- packages/extension/src/components/DaSidebar.vue
Seached tags that were not part of the popular tags list were bugged and the user was unable to actually enable them
Closes dailydotdev/daily#163
> fix(extension): show enabled tags even if not popular

- packages/components/__tests__/DaDropdown.js
- packages/components/__tests__/DaEditableText.js
- packages/components/__tests__/DaSearch.js
- packages/components/__tests__/DaSearchField.js
- packages/components/__tests__/DaTextField.js
- packages/components/package.json
- packages/components/src/common/domHelper.js
- packages/components/src/components/DaSearch.vue
- packages/components/yarn.lock
- packages/extension/__tests__/DaBookmarkList.js
- packages/extension/__tests__/DaCreateList.js
- packages/extension/__tests__/DaFeed.js
- packages/extension/__tests__/DaHeader.js
- packages/extension/__tests__/DaIntegrations.js
- packages/extension/__tests__/DaNewSource.js
- packages/extension/__tests__/DaProfile.js
- packages/extension/__tests__/DaSidebar.js
- packages/extension/__tests__/Home.js
- packages/extension/package.json
- packages/extension/src/routes/Home.vue
- packages/extension/yarn.lock
- packages/services/yarn.lock
Update dependencies due to security issues. Used `yarn upgrade-interactive` to update all dependencies as well
> chore: update deps

- packages/extension/src/components/DaHeader.vue
> Make recently visited websites prominent on the top bar. Avoid favicon cropping. 

- packages/components/src/common/postMixin.js
- packages/extension/src/manifest/development.json
- packages/extension/src/store/plugins/cache.js
For some reason, Firefox cache was broken due to Vue reactive object.
It is now fixed using json stringify and parse.
Closes dailydotdev/daily#195
> fix: caching issue in firefox

- packages/components/src/components/DaSwitch.vue
- packages/extension/src/components/DaHeader.vue
- packages/extension/src/components/DaSettings.vue
Due to timing issues the optional permission request was blocked by the browser.
Now the request is triggered immmediately with the mouse click event which fixes the issue.
Add padding to the icons of the recently visited sites
> fix: allow toggling on/off recently visited sites

- packages/extension/src/store/plugins/cache.js
Following #230, I added the `sortBy` property to the cache to make sure it is saved between sessions.
Closes #230
> feat: save the last used sort by

- packages/extension/src/apollo.js
- packages/extension/src/common/consts.js
- packages/extension/src/components/DaFeed.vue
- packages/extension/src/routes/Home.vue
The rate of opening a daily.dev tab is very high and create load on our servers.
I decided to set the websocket connection to lazy and subscribe to postsEngaged as part of the engagement requests phase
> refactor: delay websocket connection to engagement phase

- packages/components/src/common/postMixin.js
- packages/components/src/components/DaCardPost.vue
- packages/components/src/components/DaCounter.vue
- packages/components/src/components/DaInsanePost.vue
- packages/extension/src/components/DaFeed.vue
- packages/extension/src/graphql/feed.js
When opening a new tab and seeing this counter animation all-around can very distractive.
I disabled the animation until the first feed page is loaded from the server.
> refactor: disable counter animation before loading the first page

- packages/extension/__tests__/ui.js
- packages/extension/src/routes/Home.vue
- packages/extension/src/store/modules/ui.js
- packages/extension/src/store/modules/user.js
Call the /users/me endpoint to refresh the access token before dispatching any other request
> refactor: validate authentication before proceeding with other requests
