.gitignore, packages/extension/.env.local, packages/extension/.gitignore
Add .env file for local environment
=> refactor: add local environment variables file

CONTRIBUTING.md, README.md
* Update the main readme file to help others dive into the project and be able to contribute.
* Add contributing file which refers to the one on the main repository
=> docs: update readme and add contributing

packages/components/__tests__/DaCardPost.js, packages/components/__tests__/DaInsanePost.js, packages/components/src/components/DaCardPost.vue, packages/components/src/components/DaInsanePost.vue
Remove the space between tags when presented on both card and insane mode
=> refactor(extension): change the look of tags in post

packages/components/README.md, packages/components/src/components/DaInsanePost.vue, packages/components/stories/DaContext.stories.js, packages/components/stories/DaEditableText.stories.js, packages/components/stories/DaIconToggle.stories.js, packages/components/stories/DaInsanePost.stories.js, packages/components/stories/DaModal.stories.js, packages/components/stories/DaModeSwitch.stories.js, packages/components/stories/DaSpinner.stories.js, packages/components/stories/DaSwitch.stories.js, packages/components/stories/DaTerminal.stories.js, packages/components/stories/icon.stories.js, packages/components/stories/style.pcss
Add stories for the following components:
* DaContext
* DaEditableText
* DaIconToggle
* DaInsanePost
* DaModal
* DaModeSwitch
* DaSpinner
* DaSwitch
* DaTerminal
* icons
=> feat(storybook): add stories for missing components

packages/extension/README.md
Separate development section first and than production section
=> refactor(extension): update readme build section

packages/components/.gitignore, packages/components/src/components/DaCardPlaceholder.vue, packages/components/src/components/DaInsanePlaceholder.vue, packages/components/src/styles/insane.pcss, packages/components/src/styles/placeholder.pcss, packages/components/stories/DaCardPlaceholder.stories.js, packages/components/stories/DaInsanePlaceholder.stories.js, packages/components/stories/style.pcss
Two additional components which serve as placeholder while loading content. One for card mode and the other for insane mode.
=> feat(components): placeholder components

packages/components/__tests__/DaCardPost.js, packages/components/__tests__/DaInsanePost.js, packages/components/src/components/DaCardPost.vue, packages/components/src/components/DaInsanePost.vue, packages/extension/__tests__/Home.js, packages/extension/src/routes/Home.vue
Implement feature #16 
I wasn't sure if I need to add test for Home.vue, also what kind of local environment are you running your local development on? I'm using windows but running everything through the windows subsystem for linux and it was tricky getting everything working but that might just be me 😢
=> feat: navigate to publication when clicking on the logo

packages/extension/__tests__/DaSidebar.js, packages/extension/src/components/DaSidebar.vue
=> feat: search for publications

packages/components/src/components/DaCardPost.vue, packages/components/src/components/DaContext.vue, packages/components/src/components/DaInsanePost.vue, packages/extension/.editorconfig, packages/extension/__tests__/Home.js, packages/extension/__tests__/ui.js, packages/extension/src/components/DaHeader.vue, packages/extension/src/routes/Home.vue, packages/extension/src/standalone/standalone.js, packages/extension/src/store/modules/ui.js, packages/extension/src/store/plugins/cache.js, packages/moderator/__tests__/Approvals.js, packages/moderator/__tests__/RequestsView.js, packages/moderator/__tests__/fixtures/helpers.js
=> fix: design issues of the context and dnd functionality

packages/components/src/components/DaCardPost.vue, packages/components/src/components/DaInsanePost.vue, packages/extension/__tests__/feed.js, packages/extension/src/components/DaHeader.vue, packages/extension/src/routes/Home.vue, packages/extension/src/store/modules/feed.js, packages/services/__tests__/content.ts, packages/services/src/content.ts
When reporting a post or choosing to hide a post, the post will be removed immediately from the feed of the user.
Please refer to https://github.com/dailynowco/daily/issues/88
=> feat: hide post from feed

packages/extension/__tests__/Step2.js, packages/extension/src/routes/Step2.vue
=> feat(extension): add skip button during onboarding (#35)

packages/components/.storybook/config.js, packages/components/__tests__/DaCardPost.js, packages/components/__tests__/DaInsanePost.js, packages/components/src/components/DaCardPost.vue, packages/components/src/components/DaInsanePost.vue, packages/components/src/styles/tooltip.pcss, packages/extension/__tests__/DaHeader.js, packages/extension/__tests__/DaSidebar.js, packages/extension/__tests__/Home.js, packages/extension/package.json, packages/extension/src/components/DaHeader.vue, packages/extension/src/components/DaSidebar.vue, packages/extension/src/standalone/standalone.js
=> refactor(extension): add custom tooltips

packages/components/src/components/DaSwitch.vue, packages/components/stories/DaSwitch.stories.js
=> feat(components): small variant of switch

packages/extension/__tests__/DaFeed.js, packages/extension/__tests__/Home.js, packages/extension/__tests__/fixtures/helpers.js, packages/extension/src/components/DaFeed.vue, packages/extension/src/routes/Home.vue, yarn.lock
The feed component is a standalone component which presents a complete feed of posts.
The component takes care of bookmarking, reporting and all the interaction needed with the posts.
The feed takes into account the user preferences (cards/insane).
Related to #52
=> refactor(extension): create a feed component

packages/extension/bundlesize.config.json, packages/extension/package.json, packages/extension/vue.config.js, yarn.lock
Reduce bundle size by targeting right browsers and also setup a bundlesize GitHub check.
Closes #55
=> build(extension): reduce bundle size

packages/components/__tests__/DaCardPost.js, packages/components/__tests__/DaInsanePost.js, packages/components/__tests__/mdyDateFilter.js, packages/components/src/common/mdyDateFilter.js, packages/components/src/components/DaCardPost.vue, packages/components/src/components/DaInsanePost.vue
mdyDateFilter compares a given time to the current time and decides which string to return based on the following specs:
* time diff < 1 minute => "now"
* time diff < 1 hour => time ago in minutes
* time diff < 48 hours => time ago in hours
* Otherwise, formatted date string
=> refactor(components): update mdyDateFilter to conditional formatting

packages/components/src/components/DaCardPost.vue, packages/components/src/components/DaInsanePost.vue, packages/components/stories/DaCardPost.stories.js, packages/components/stories/DaInsanePost.stories.js, packages/extension/src/components/DaFeed.vue, packages/services/__tests__/content.ts, packages/services/src/content.ts
Add a state for both insane and card posts which indicates that this post was read by the user already.
Closes #42
=> feat(extension): read indicator for posts

packages/components/__tests__/DaRadio.js, packages/components/__tests__/DaRadioItem.js, packages/components/src/components/DaCardPost.vue, packages/components/src/components/DaRadio.vue, packages/components/src/components/DaRadioItem.vue, packages/components/stories/DaRadio.stories.js, packages/components/stories/DaRadioItem.stories.js
DaRadio is a new component for easily embedding a radio button in the app.
It is based on the native radio input of HTML for accessibility reasons.
Closes #49
Related to #52
=> feat(components): radio button component

packages/components/src/directives/tooltip.js
* Tooltip was not position correctly after scrolling
* Tooltip did not disappear when element is removed from DOM
=> fix(components): tooltip issues

packages/components/__tests__/DaIconToggle.js, packages/components/__tests__/DaInsanePost.js, packages/components/__tests__/DaModeSwitch.js, packages/components/__tests__/DaSwitch.js, packages/components/src/components/DaCard.vue, packages/components/src/components/DaInsanePost.vue, packages/components/src/components/DaModeSwitch.vue, packages/components/src/components/DaRadio.vue, packages/components/src/components/DaRadioItem.vue, packages/components/src/styles/insane.pcss, packages/components/stories/DaModeSwitch.stories.js, packages/extension/__tests__/DaHeader.js, packages/extension/__tests__/DaSettings.js, packages/extension/__tests__/ui.js, packages/extension/src/components/DaFeed.vue, packages/extension/src/components/DaHeader.vue, packages/extension/src/components/DaLayoutPreview.vue, packages/extension/src/components/DaProfile.vue, packages/extension/src/components/DaSettings.vue, packages/extension/src/routes/Home.vue, packages/extension/src/standalone/App.vue, packages/extension/src/store/modules/ui.js, packages/extension/src/store/plugins/cache.js, packages/extension/src/store/plugins/sync.js, packages/services/__tests__/profile.ts, packages/services/src/profile.ts
New layout settings for changing the look of the feel.
These settings can be found in a panel that is shown when clicking on a button in the header.
Closes #50
Closes #52
=> feat(extension): layout settings

packages/components/src/components/DaSearch.vue, packages/extension/__tests__/DaFeed.js, packages/extension/__tests__/Home.js, packages/extension/__tests__/feed.js, packages/extension/src/components/DaFeed.vue, packages/extension/src/routes/Home.vue, packages/extension/src/store/modules/feed.js
When transitioning from empty search screen to any other feed, it messed `DaLineClamp`.
=> fix(extension): tags overflow from post

packages/extension/src/ctas.js
Remove medium link since it's not a priority/focus for now.
=> UPDATE: remove medium link

packages/extension/src/ctas.js
Update links for the new domain.
=> 👌 UPDATE CTA Links

packages/extension/src/components/DaHeader.vue, packages/extension/src/components/DaProfile.vue, packages/extension/src/ctas.js
Update the extension with new links.
=> 👌 UPDATE: add the new links

packages/components/src/components/DaCardPost.vue, packages/extension/src/common/keyNavigationService.js, packages/extension/src/components/DaFeed.vue, packages/extension/src/routes/Home.vue
When a user report a post with a broken link or nsfw, the app throws undefined error. This issue now resolved.
Closes dailydotdev/daily#143
=> fix: unexpected error when reporting about post

packages/extension/src/routes/Home.vue
For this issue: [Inifinite Scroll Problem](https://github.com/dailydotdev/daily/issues/144) i made a little fix.
=> fixed failure to load problem on scroll down

packages/extension/src/routes/Home.vue
Changes the button text from end to center in the message.
=> 👌 IMPROVE: align text from end to center

packages/components/__tests__/DaCardPost.js, packages/components/__tests__/DaInsanePost.js, packages/components/__tests__/mdyDateFilter.js, packages/components/src/common/mdyDateFilter.js, packages/components/src/posts.json
=> feat(components): improve date format in card footers

packages/extension/__tests__/DaSettings.js, packages/extension/__tests__/ui.js, packages/extension/src/components/DaSettings.vue, packages/extension/src/store/modules/feed.js, packages/extension/src/store/modules/ui.js, packages/extension/src/store/plugins/sync.js, packages/services/__tests__/profile.ts, packages/services/src/content.ts, packages/services/src/profile.ts
=> feat(posts): Added hide read posts setting

packages/components/__tests__/DaSearchField.js, packages/components/src/components/DaSearchField.vue, packages/components/src/styles/themes.pcss, packages/components/stories/DaSearchField.stories.js, packages/extension/src/standalone/App.vue
`DaSearchField` is a new design system component for getting text input from the user mostly for search purposes
=> feat(components): search field component

packages/components/__tests__/DaTextField.js, packages/components/src/common/textFieldMixin.js, packages/components/src/components/DaSearchField.vue, packages/components/src/components/DaTextField.vue, packages/components/src/styles/fields.pcss, packages/components/src/styles/global.pcss, packages/components/stories/DaTextField.stories.js
`DaTextField` is a design system component that encapsulate the default input element with custom design and behavior
=> feat(components): text field component

packages/extension/src/common/keyNavigationService.js, packages/extension/src/routes/Home.vue
As discussed, the `key` event for `esc` should return back the user to home page.
Note: I've migrated from using `keypress` to `keydown` as it allows more key to be used.
Please let me know if you have further concerns regarding this PR. Thank you very much for understanding ❤️
=> Feat: `esc` key binding - Technical Issue #91

packages/components/__tests__/DaTextField.js, packages/components/src/components/DaTextField.vue, packages/extension/__tests__/DaProfile.js, packages/extension/src/common/updateProfileMixin.js, packages/extension/src/components/DaConfirmAccount.vue, packages/extension/src/components/DaProfile.vue
* Trigger validity event even when the first input is valid
* Fix the padding of the navigation menu in the profile dialog
* Confirm profile when hitting enter in the Profile Confirmation dialog
Closes dailydotdev/daily#156
=> fix: multiple issues with the new profile dialogs

packages/extension/.eslintrc.js, packages/extension/.graphqlconfig, packages/extension/__tests__/DaSidebar.js, packages/extension/__tests__/Home.js, packages/extension/__tests__/feed.js, packages/extension/__tests__/fixtures/helpers.js, packages/extension/apollo.config.js, packages/extension/babel.config.js, packages/extension/package.json, packages/extension/src/__mocks__/apollo.js, packages/extension/src/apollo.js, packages/extension/src/common/graphql.js, packages/extension/src/common/post.js, packages/extension/src/routes/Home.vue, packages/extension/src/standalone/standalone.js, packages/extension/src/store/modules/feed.js, packages/extension/yarn.lock, packages/services/src/index.ts
Migrate to fetch feeds using the new API and Apollo Client
=> refactor(extension): fetch feeds of api v2

packages/extension/__tests__/DaProfile.js, packages/extension/src/components/DaProfile.vue, packages/extension/src/components/DaSidebar.vue, packages/extension/src/routes/Home.vue
Add premium badge and relevant links to the profile popup of a premium user.
=> feat: add premium marks to the profile popup

packages/extension/__tests__/DaNewSource.js, packages/extension/src/components/DaNewSource.vue, packages/extension/src/graphql/newSource.js
* Send the website of the private source when adding a new one
* Update immediately the source list in the sidebar upon adding a new private source
=> fix: add new private source issues

packages/components/src/components/DaSwitch.vue, packages/components/src/styles/buttons.pcss, packages/components/src/styles/global.pcss, packages/components/src/styles/themes.pcss, packages/extension/src/components/DaConfirmAccount.vue, packages/extension/src/components/DaHeader.vue, packages/extension/src/components/DaIntegrations.vue, packages/extension/src/components/DaProfile.vue, packages/extension/src/routes/Home.vue
Change the dark mode theme with minor tweaks to improve contrast
=> refactor: update color palette and minor fixes

packages/components/src/components/DaCard.vue, packages/components/src/components/DaInsaneAd.vue, packages/components/src/components/DaInsanePost.vue, packages/extension/__tests__/DaFeed.js, packages/extension/__tests__/Home.js, packages/extension/__tests__/__snapshots__/DaIntegrations.js.snap, packages/extension/__tests__/__snapshots__/DaNewSource.js.snap, packages/extension/__tests__/ui.js, packages/extension/src/background.js, packages/extension/src/common/cache.js, packages/extension/src/components/DaFeed.vue, packages/extension/src/components/DaIntegrations.vue, packages/extension/src/components/DaNewSource.vue, packages/extension/src/components/DaProfile.vue, packages/extension/src/components/DaReferral.vue, packages/extension/src/routes/Home.vue, packages/extension/src/store/modules/ui.js, packages/moderator/src/components/DmHeader.vue
There are 4 criteria for actively asking the users to share daily with their friends.
Links reverted back to target _blank due to user feedback.
=> feat: open referral popup on several win moments

packages/components/package.json, packages/components/src/common/mdyDateFilter.js, packages/components/src/styles/cards.pcss, packages/components/src/styles/global.pcss, packages/components/yarn.lock, packages/extension/package.json, packages/extension/src/components/DaFeed.vue, packages/extension/src/components/DaNewSource.vue, packages/extension/src/components/DaSidebar.vue, packages/extension/yarn.lock
Drop the masonry grid in favor of the native css grid.
This change should increase drastically the performance.
=> refactor: use css grid

packages/components/__tests__/DaCardPost.js, packages/components/__tests__/DaInsanePost.js, packages/components/src/common/postMixin.js, packages/extension/__tests__/DaFeed.js, packages/extension/__tests__/feed.js, packages/extension/src/common/post.js, packages/extension/src/components/DaFeed.vue, packages/extension/src/graphql/feed.js, packages/extension/src/store/modules/feed.js, packages/services/__tests__/monetization.ts, packages/services/package.json, packages/services/src/auth.ts, packages/services/src/content.ts, packages/services/src/monetization.ts, packages/services/src/profile.ts, packages/services/src/utils.ts, packages/services/yarn.lock
The upvote button is now integrated to the API server.
Upon click the upvote state will be toggled.
=> feat: upvote

packages/components/src/common/postMixin.js, packages/components/src/components/DaCardPost.vue, packages/components/src/components/DaInsanePost.vue, packages/components/stories/DaCardPost.stories.js, packages/components/stories/DaInsanePost.stories.js, packages/extension/__tests__/DaFeed.js, packages/extension/__tests__/DaNewSource.js, packages/extension/src/common/keyNavigationService.js, packages/extension/src/components/DaFeed.vue, packages/extension/src/graphql/feed.js
Upon an upvote or post click, the comment popup is shown to motivate the user to submit a new comment and start a discussion
=> feat: submit first comment

packages/components/src/components/DaCardPost.vue, packages/components/src/components/DaInsanePost.vue, packages/components/src/posts.json, packages/extension/src/graphql/feed.js
Fetch featured comments of post and show them on the card or list item
=> feat: featured comments

packages/components/src/commentPopupText.js, packages/components/src/common/postMixin.js, packages/components/src/components/DaCardPost.vue, packages/components/src/components/DaInsanePost.vue, packages/extension/__tests__/DaFeed.js, packages/extension/src/common/cache.js, packages/extension/src/components/DaFeed.vue, packages/extension/src/routes/Home.vue
Non-users should be promoted to sign-in before upvoting or commenting on a post
=> feat: non-users flow for upvote and comments

packages/components/src/common/postMixin.js, packages/components/src/components/DaCardPost.vue, packages/extension/__tests__/DaSettings.js, packages/extension/__tests__/ui.js, packages/extension/src/components/DaFeed.vue, packages/extension/src/components/DaSettings.vue, packages/extension/src/store/modules/ui.js, packages/extension/src/store/plugins/sync.js, packages/services/__tests__/profile.ts, packages/services/src/profile.ts
Related [PR](https://github.com/dailydotdev/daily-apps/pull/135).
Hi Team,
As I was unable to push changes on OP's forked repo, I had to create a separate PR for the feature request.
Opening New Tab when hitting the links should be based on the user's preference and the default value should be `true`.
Kindly check the changes and please just send feedback with regards to this PR if there's any issue or concern so I can further make the necessary changes.
Thank you!
Best Regards,
Lee
=> Feat: Open New Tab Settings

packages/extension/src/routes/Home.vue
=> feat: hide cta for premium users

packages/extension/src/components/DaFeed.vue
Here are the new width according to the user's settings:
Eco -> full width
Roomy -> 1200px
Cozy -> 960px
=> feat: increase the max width of insane mode

packages/components/src/components/DaCardPost.vue, packages/components/src/components/DaInsanePost.vue, packages/extension/__tests__/DaFeed.js, packages/extension/__tests__/feed.js, packages/extension/src/components/DaFeed.vue, packages/extension/src/graphql/feed.js, packages/extension/src/store/modules/feed.js
When number is greater than zero show the number of upvotes and comments on the post
=> feat: show number of upvotes and comments

packages/components/package.json, packages/components/src/common/mdyDateFilter.js, packages/components/yarn.lock
The date filter had some issues with isToday and isYesterday checks.
To fix it, I decided to use date-fns. Make it super easy
=> fix: date filter

packages/extension/__tests__/feed.js, packages/extension/src/graphql/feed.js, packages/extension/src/store/modules/feed.js
To reduce server overhead, I reduced the requested field in the subscription only to the necessary fields
=> refactor: reduce subscription fields

packages/extension/__tests__/DaSidebar.js, packages/extension/__tests__/Home.js, packages/extension/__tests__/ui.js, packages/extension/src/components/DaSidebar.vue, packages/extension/src/routes/Home.vue, packages/extension/src/standalone/App.vue, packages/extension/src/store/modules/ui.js
Instead of hovering, the user has to click on a the button to show/hide the sidebar.
In terms of UX, it is so much clearer and easier to use
=> feat: new sidebar mechanism

packages/extension/.gitignore, packages/extension/__tests__/DaHeader.js, packages/extension/__tests__/ui.js, packages/extension/src/background.js, packages/extension/src/common/cache.js, packages/extension/src/components/DaHeader.vue, packages/extension/src/routes/Home.vue, packages/extension/src/store/modules/ui.js
Introducing a new mode for the extension, minimal UI.
This mode is active for the first few visits.
=> feat: reduce buttons for the first visits of the user

packages/components/src/components/DaRank.vue, packages/components/src/components/DaRankProgress.vue, packages/extension/__tests__/Home.js, packages/extension/src/routes/Home.vue
Create a partial onboarding process to walk new users through the reading ranks and discover some features
=> feat: welcome balloon and ranking walkthrough

packages/components/src/components/DaCardAd.vue, packages/components/src/components/DaCardPost.vue, packages/components/src/components/DaInsaneAd.vue, packages/components/src/components/DaInsanePost.vue, packages/extension/__tests__/DaFeed.js, packages/extension/__tests__/Home.js, packages/extension/__tests__/ui.js, packages/extension/src/components/DaFeed.vue, packages/extension/src/components/DaRankPopup.vue, packages/extension/src/components/DaUnlockUiModal.vue, packages/extension/src/routes/Home.vue, packages/extension/src/standalone/App.vue, packages/extension/src/store/modules/ui.js
After the first post click, a modal is shown and the full ui is unlocked
=> feat: unlock full ui

packages/components/src/components/DaScroll.vue, packages/components/yarn.lock, packages/extension/src/routes/Home.vue
Show scroll to top button with animation, when the user scrolls more than 50% of the screen.
=> Add scroll to top button

packages/extension/__tests__/DaHeader.js, packages/extension/__tests__/Home.js, packages/extension/src/components/DaBanner.vue, packages/extension/src/components/DaHeader.vue, packages/extension/src/routes/Home.vue
related to https://github.com/dailydotdev/daily/issues/225
=> Fix banners above header and rank-btn 
